name: CI
on:
  push:
    branches: main
  pull_request:
    branches: 
      - main
      - develop
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository one
        uses: actions/checkout@v3